"""
Package an `e2e.ml.dataset`-style radar corpus into a self-contained bundle an
outsider can use with **no access to this repository**: they get the frames, the
manifest, a numpy-only decode spec (`DATA_FORMAT.md`), attribution/licensing terms,
a checksum manifest, and a README spelling out the exact three commands (generate ->
train -> eval) against the bundle's own paths.

This module does not generate or re-encode any data -- it only copies/hardlinks
files that already exist under a `generate_dataset`/`chain_generate` manifest
directory (see `e2e.ml.dataset`'s "On-disk dataset layout" docstring) into a new
bundle directory, plus writes the four small text files above.

CLI
---
    python -m e2e.ml.export_corpus --manifest <path/to/manifest.json> --out <bundle_dir> \\
        [--link] [--dry-run]

`--link` hardlinks frame/manifest files into the bundle instead of copying them
(same volume only; falls back to a copy if the OS/filesystem refuses the link --
e.g. crossing a volume boundary) -- useful for a large corpus where a copy would
double disk usage. `--dry-run` prints the plan (file count, byte total, output
paths) and writes nothing, matching this repo's convention elsewhere (see
`e2e.ml.dataset --dry-run` / `e2e.environment.scenario_runner --dry-run`).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional

_HERE = Path(__file__).resolve().parent
DATA_FORMAT_SRC = _HERE / "DATA_FORMAT.md"

DATA_SUBDIR = "data"  # frames + manifest.json land under <bundle>/data/ (see _write_bundle)


# --------------------------------------------------------------------------------
# Attribution / licensing text (see e2e/ml/README.md's "Attribution & licensing"
# section, and e2e/environment/assets.py's asset-provenance comments, for the source of every
# claim below -- reproduced here, not re-derived, so this file cannot silently drift
# out of sync with the terms actually granted).
# --------------------------------------------------------------------------------
ATTRIBUTION_TEXT = """\
# Attribution & licensing

This bundle -- the synthesized radar frames, their labels, and this documentation --
was produced by the Array Processing End-to-End Simulator
(https://github.com/, MIT License; see the full license text at the bottom of this
file). You may use, copy, modify, and redistribute the DATA in this bundle under
those same MIT terms.

Two upstream attributions apply to the SOFTWARE this data is meant to be trained
with (not shipped in this bundle, but named in README.md's reproduction commands --
included here because the data has no meaning without them):

## Model ports

* **FFTRadNet** (`e2e/ml/models/fftradnet.py` in the source repo) is adapted from
  [valeoai/RADIal](https://github.com/valeoai/RADIal) (Rebut et al., "Raw
  High-Definition Radar for Multi-Task Learning", CVPR 2022). Neither upstream
  repository ships a `LICENSE` file; the adaptation carries attribution headers
  identifying the upstream source and documenting every deviation inline, and is
  used under research-community attribution norms.
  **Status: approved.** The publishing author and repository publisher confirmed in
  writing (2026-08-10) that the missing `LICENSE` was an oversight, and granted
  permission to reuse and share the code. Used with attribution on that basis.

* **SSMRadNet** (`e2e/ml/models/ssmradnet.py`, `e2e/ml/models/ssm.py` in the source
  repo) is adapted from
  [AnuvabSen1/SSMRadNet](https://github.com/AnuvabSen1/SSMRadNet).
  **Status: approved.** The authors gave written approval for this adaptation's
  redistribution (2026-08-07), on top of having requested this integration
  (training/evaluation of SSMRadNet on this simulator's synthetic data -- i.e. data
  of the kind in this bundle).

## Scene asset attributions (conditional -- see note)

If this corpus was generated via the ray-traced chain (`e2e.ml.chain_generate`,
rather than the closed-form analytic fallback `e2e.ml.dataset.generate_sample`), the
synthesized returns for vehicle-class objects were computed against real downloaded
vehicle meshes (`e2e/environment/assets.py` in the source repo). A corpus generated by
`e2e.ml.dataset.generate_sample`/`generate_dataset` (the CI/offline fallback: no
Sionna, no GPU) uses pure point scatterers and involves no mesh geometry at all --
this section does not apply to such a corpus. If in doubt, check how the corpus was
produced (the command that generated it, e.g. as recorded in this bundle's
README.md) or ask the corpus provider.

Where meshes were used:

* **Kenney "Car Kit"** (kenney.nl/assets/car-kit) -- 15 vehicle meshes (sedans, SUVs,
  vans, trucks, emergency vehicles). **License: CC0 1.0 Universal** (verified from
  the kit's own `License.txt`) -- no attribution legally required, credited here as
  good practice.
* **"3D Bus" by ajanhallinta** (opengameart.org/content/3d-bus). **License: CC0.**
* **"Tram" by Poly by Google** (poly.pizza/m/e9pQgEqPGir). **License: CC-BY 3.0 --
  attribution required.** Credit: "'Tram' by Poly by Google, licensed under
  CC-BY 3.0."
* Five additional meshes sourced from freestl.com (a DeLorean, an Audi R8 Spyder, a
  DAF truck, a trolley car, and a school bus) carry no verified license terms
  (provenance unknown/unverified at time of use).

None of the above mesh files themselves are included in this bundle -- only the
radar returns (and, where relevant, target class/extent metadata) computed from
them.

## Full MIT license text (covers the data + documentation in this bundle)

MIT License

Copyright (c) 2026 Alex Saad-Falcon

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


# --------------------------------------------------------------------------------
# Manifest inspection
# --------------------------------------------------------------------------------
def _load_manifest(manifest_path: Path) -> Dict:
    with open(manifest_path) as f:
        return json.load(f)


def _frame_files(manifest: Dict) -> List[str]:
    """Every frame filename the manifest references, deduped, in a stable order
    (train, then val, then test -- `files` splits are disjoint by construction, see
    `e2e.ml.dataset._split_bounds`, so dedup here is just defensive)."""
    files = manifest.get("files", {})
    out: List[str] = []
    seen = set()
    for split in ("train", "val", "test"):
        for fname in files.get(split, []):
            if fname not in seen:
                seen.add(fname)
                out.append(fname)
    return out


def _plan(manifest_path: Path, out_dir: Path) -> Dict:
    manifest = _load_manifest(manifest_path)
    frame_files = _frame_files(manifest)
    cfg = manifest.get("config", {}) or {}
    n_scenes = len(manifest.get("sequences", [])) or None
    total_bytes = manifest_path.stat().st_size
    src_dir = manifest_path.parent
    missing = []
    for fname in frame_files:
        p = src_dir / fname
        if p.exists():
            total_bytes += p.stat().st_size
        else:
            missing.append(fname)
    return {
        "manifest": manifest,
        "manifest_path": manifest_path,
        "src_dir": src_dir,
        "out_dir": out_dir,
        "frame_files": frame_files,
        "missing_files": missing,
        "cfg_name": cfg.get("name", "radar"),
        "tier": manifest.get("tier"),
        "n_scenes": n_scenes,
        "n_frames": len(frame_files),
        "total_bytes": total_bytes,
    }


# --------------------------------------------------------------------------------
# README (the three reproduction commands, against the bundle's own paths)
# --------------------------------------------------------------------------------
def _readme_text(plan: Dict) -> str:
    manifest = plan["manifest"]
    cfg_name = plan["cfg_name"]
    tier = plan["tier"]
    seed = manifest.get("seed", 0)
    snr_db = manifest.get("snr_db")
    frames_per_scene = manifest.get("frames_per_scene", 1)
    n_scenes = plan["n_scenes"] if plan["n_scenes"] is not None else "<n>"

    dataset_cmd = (
        f"python -m e2e.ml.dataset --config {cfg_name} --tier {tier} "
        f"--n {n_scenes} --seed {seed}"
        + (f" --snr-db {snr_db}" if snr_db is not None else "")
        + (f" --frames-per-scene {frames_per_scene}" if frames_per_scene != 1 else "")
        + " --out <where you want a NEW corpus written>"
    )
    manifest_rel = f"{DATA_SUBDIR}/manifest.json"
    train_cmd = (
        f"python -m e2e.ml.train --manifest {manifest_rel} --model fftradnet --epochs 25"
    )
    eval_cmd = (
        f"python -m e2e.ml.train --manifest {manifest_rel} "
        f"--eval-only <manifest_dir>/runs/fftradnet/best.pt --split test"
    )

    return f"""\
# Radar corpus bundle: {cfg_name} / tier {tier}

This bundle is self-contained: the frames, the manifest, and the decode spec
(`DATA_FORMAT.md`) travel together, so you can read every array in `{DATA_SUBDIR}/`
with numpy alone -- no access to the generating repository is required (see
`DATA_FORMAT.md`). Licensing/attribution terms are in `ATTRIBUTION.md`. Verify the
transfer with `MANIFEST.sha256` (see below).

Layout:

    README.md          this file
    DATA_FORMAT.md      numpy-only decode spec for every array in {DATA_SUBDIR}/
    ATTRIBUTION.md      licensing + upstream attribution terms
    MANIFEST.sha256     sha256 of every file in this bundle
    {DATA_SUBDIR}/manifest.json   the corpus manifest (train/val/test split, radar config, ...)
    {DATA_SUBDIR}/*.npz            {plan['n_frames']} frame file(s)

## Reproducing training

Reading the frame data needs nothing beyond `{DATA_SUBDIR}/` + numpy (see
`DATA_FORMAT.md`). Training/evaluating a model needs a checkout of the generating
repository, `e2e_sim_public`.

This corpus was generated with (recorded in `{DATA_SUBDIR}/manifest.json`):

    {dataset_cmd}

Run this (from the repo root) only if you want to generate MORE data in the same
style -- the frames already in `{DATA_SUBDIR}/` do not need regenerating.

1. (optional -- see above) Generate a fresh corpus:

       {dataset_cmd}

2. Train a model against THIS bundle's manifest (copy/symlink `{DATA_SUBDIR}/` into
   your repo checkout first, or pass an absolute path to `--manifest`):

       {train_cmd}

3. Evaluate the resulting checkpoint on the held-out test split:

       {eval_cmd}

`--model` may be `fftradnet` or `ssmradnet` (see `ATTRIBUTION.md` for both models'
provenance/approval status). `e2e.ml.train`'s other flags (`--epochs`, `--batch-size`,
`--lr`, `--gamma`, ...) are documented via `python -m e2e.ml.train --help`.

## Verifying the transfer

    sha256sum -c MANIFEST.sha256

(or, without `sha256sum`: recompute each listed file's sha256 and compare to the
hex digest on its line).
"""


# --------------------------------------------------------------------------------
# Checksum manifest
# --------------------------------------------------------------------------------
def _sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_checksum_manifest(bundle_dir: Path, relative_paths: List[str]) -> Path:
    """Write `MANIFEST.sha256` in `sha256sum -c`-compatible format: `<hexdigest>  <path>`
    (two spaces, POSIX-style forward-slash relative paths -- checked with `-c` on any
    platform sha256sum runs on)."""
    lines = []
    for rel in sorted(relative_paths):
        digest = _sha256_of(bundle_dir / rel)
        lines.append(f"{digest}  {rel.replace(os.sep, '/')}")
    out_path = bundle_dir / "MANIFEST.sha256"
    # newline="\n": force LF line endings regardless of host OS -- `sha256sum -c`
    # (a POSIX tool) chokes on a CRLF-terminated filename (reads it as part of the
    # path), so this file must stay LF-only even when built on Windows.
    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    return out_path


# --------------------------------------------------------------------------------
# File placement (copy or hardlink)
# --------------------------------------------------------------------------------
def _place(src: Path, dst: Path, *, link: bool) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        dst.unlink()
    if link:
        try:
            os.link(src, dst)
            return
        except OSError:
            pass  # cross-volume or unsupported -- fall back to a copy
    shutil.copy2(src, dst)


# --------------------------------------------------------------------------------
# Bundle assembly
# --------------------------------------------------------------------------------
def export_corpus(manifest_path, out_dir, *, link: bool = False) -> Path:
    """Assemble a self-contained bundle at `out_dir` from a `generate_dataset`/
    `chain_generate` manifest at `manifest_path`. Returns `out_dir`.

    Raises `FileNotFoundError` if any frame file the manifest references is missing
    from `manifest_path`'s directory -- a corpus that can't losslessly copy is not
    safe to ship.
    """
    manifest_path = Path(manifest_path).resolve()
    out_dir = Path(out_dir).resolve()
    plan = _plan(manifest_path, out_dir)
    if plan["missing_files"]:
        raise FileNotFoundError(
            f"{len(plan['missing_files'])} frame file(s) referenced by "
            f"{manifest_path} are missing from {plan['src_dir']}: "
            f"{plan['missing_files'][:5]}{'...' if len(plan['missing_files']) > 5 else ''}"
        )

    data_dir = out_dir / DATA_SUBDIR
    data_dir.mkdir(parents=True, exist_ok=True)

    relative_paths: List[str] = []

    _place(manifest_path, data_dir / "manifest.json", link=link)
    relative_paths.append(f"{DATA_SUBDIR}/manifest.json")
    for fname in plan["frame_files"]:
        _place(plan["src_dir"] / fname, data_dir / fname, link=link)
        relative_paths.append(f"{DATA_SUBDIR}/{fname}")

    shutil.copy2(DATA_FORMAT_SRC, out_dir / "DATA_FORMAT.md")
    relative_paths.append("DATA_FORMAT.md")

    (out_dir / "ATTRIBUTION.md").write_text(ATTRIBUTION_TEXT)
    relative_paths.append("ATTRIBUTION.md")

    (out_dir / "README.md").write_text(_readme_text(plan))
    relative_paths.append("README.md")

    _write_checksum_manifest(out_dir, relative_paths)
    return out_dir


# --------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------
def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m e2e.ml.export_corpus",
        description="Package a generated e2e.ml radar corpus into a self-contained, "
                    "self-describing bundle (frames + manifest + decode spec + "
                    "attribution + checksums + a reproduction README).",
    )
    p.add_argument("--manifest", required=True, help="path to a generate_dataset/chain_generate manifest.json")
    p.add_argument("--out", required=True, help="output bundle directory (created if missing)")
    p.add_argument("--link", action="store_true",
                   help="hardlink frame/manifest files into the bundle instead of copying "
                        "(same volume only; falls back to a copy otherwise)")
    p.add_argument("--dry-run", action="store_true",
                   help="print the packaging plan without writing anything")
    return p


def main(argv: Optional[List[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)
    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"manifest not found: {manifest_path}", file=sys.stderr)
        return 2
    out_dir = Path(args.out)

    plan = _plan(manifest_path.resolve(), out_dir.resolve())
    if args.dry_run:
        print("=" * 70)
        print(f"manifest:     {manifest_path}")
        print(f"config/tier:  {plan['cfg_name']} / {plan['tier']}")
        print(f"scenes:       {plan['n_scenes']}")
        print(f"frames:       {plan['n_frames']}")
        print(f"est. size:    {plan['total_bytes'] / 1e6:.2f} MB (manifest + frame files, on-disk sizes)")
        if plan["missing_files"]:
            print(f"MISSING:      {len(plan['missing_files'])} frame file(s) not found under {plan['src_dir']}")
        print(f"out:          {out_dir}  (NOT written -- dry-run)")
        print(f"  {out_dir}/README.md")
        print(f"  {out_dir}/DATA_FORMAT.md")
        print(f"  {out_dir}/ATTRIBUTION.md")
        print(f"  {out_dir}/MANIFEST.sha256")
        print(f"  {out_dir}/{DATA_SUBDIR}/manifest.json")
        print(f"  {out_dir}/{DATA_SUBDIR}/<{plan['n_frames']} frame file(s)>")
        print("=" * 70)
        return 0

    export_corpus(manifest_path, out_dir, link=args.link)
    print(f"wrote bundle to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
