"""
Corpus statistical-validation reporter for `e2e.ml` radar datasets.

Implements sections 1-2 and 5 of the panel's stats-design review (the difficulty-
ladder training protocol in section 3 is a separate, orchestrator-run shard). Reads
ONLY `manifest.json` + each frame's cheap "meta" npz entry (no `adc`/`labels` array
reload) for the corpus-composition checks in `collect_stats`; an OPTIONAL,
deterministic tensor-level sample (`tensor_sample_per_split`) additionally loads a
few frames/split via `e2e.ml.dataset.RadarFrameDataset` for input-magnitude
statistics that cannot be derived from meta alone.

Radial-velocity approximation (documented, not exact)
-------------------------------------------------------
`meta["targets"]` gives `(range_m, sin_az, class)`; `meta["target_extras"]` gives the
target's full 3-vector `velocity_mps` but NOT its position. To recover a radial
(line-of-sight) velocity component from `(range_m, sin_az, velocity_mps)` alone, this
module reconstructs the line-of-sight *direction* (not the position, which is not
needed for a velocity projection) in the scene's own frame -- radar at the origin,
boresight along `+x`, ULA axis along `+y` -- exactly as `e2e.ml.scenes._sample_fov_position`
places targets and `e2e.ml.labels._range_sin_az` derives `(r, sin_az)`:

    cos_az = sqrt(1 - sin_az**2)          # targets stay in front of the array (cos_az > 0)
    unit_los = (cos_az, sin_az, 0.0)
    v_radial = velocity_mps . unit_los

This is exact for every corpus generated by `e2e.ml.scenes.sample_scene` (the radar
node is always at the origin with that exact boresight/axis convention -- see
`sample_scene`'s `Node(... position=(0,0,0), look_at=(1,0,0))`); it would be an
approximation (ignoring the radar's own pose) for any future scene source that moves
the radar node itself. Flagged here rather than silently assumed.

Clamp-saturation check (design doc section 2.1)
-------------------------------------------------
`e2e.ml.scenes._sample_velocity` clamps a target's radial speed to
`_RADIAL_VELOCITY_FRAC (0.8) * cfg.max_velocity_mps` so training frames never alias in
Doppler; the design doc's key calibration finding is that a large fraction of D2/D3
targets sit AT that clamp cap, meaning their sampled speed range does not actually show
up as a wider realized Doppler distribution. `CLAMP_FRAC`/`CLAMP_TOL` below mirror
`scenes.py`'s constant (duplicated as a plain float, not imported, since this module's
meta-only pass has no `Scenario`/`TierSpec` objects to read it off of) -- a target's
`|v_radial|` within `CLAMP_TOL` (relative) of the cap counts as "clamp-saturated".
`CLAMP_FLAG_THRESHOLD` is the design doc's recommended report flag (>15%).

Tensor-level sample caveat
---------------------------
The optional tensor pass computes a **measured** per-frame peak-to-median-floor power
ratio (dB) from the derived range-Doppler input -- this is NOT the same quantity as
`meta["snr_db"]` (the synthesizer's *target* input SNR for its single strongest
scatterer, a global config knob, see `rd_synth.synthesize_adc`'s docstring). The
measured ratio reflects the realized peak power over the WHOLE cube's median (a crude
noise-floor proxy, not a matched-filter SNR) and will differ from `snr_db` for weaker/
farther/lower-RCS targets or multi-target frames. Keep the two numbers in separate
report sections; do not conflate them.

CLI
---
    python -m e2e.ml.stats_report --manifest PATH [--out report.md] [--tensor-sample 50]
    python -m e2e.ml.stats_report --compare M1 M2 M3 M4 --out combined.md
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

import numpy as np
import torch

# Mirrors e2e.ml.scenes._RADIAL_VELOCITY_FRAC (duplicated as a plain float -- see the
# module docstring for why this module doesn't import e2e.ml.scenes directly).
CLAMP_FRAC = 0.8
# "within 2% of the cap" (design doc section 2.1), relative to the cap's own magnitude.
CLAMP_TOL = 0.02
# Design doc section 2.1: flag a corpus whose clamp-saturation rate exceeds this.
CLAMP_FLAG_THRESHOLD = 0.15
# Design doc section 2.2: footprint overlap is expected to be exactly 0% at the shipped
# grid resolution; flag ANY nonzero overlap fraction as worth a second look.
OVERLAP_FLAG_THRESHOLD = 0.0

# Ground-truth classes (mirrors e2e.ml.dataset.LABEL_CLASSES; duplicated for the same
# reason as CLAMP_FRAC above -- this module reads meta/npz only, no sibling imports
# needed beyond RadarConfig/RadarFrameDataset).
LABEL_CLASSES = ("vehicle", "pedestrian")

_EPS = 1e-12


# --------------------------------------------------------------------------------
# Small numeric helpers
# --------------------------------------------------------------------------------
def _radial_velocity(sin_az: float, velocity_mps: Sequence[float]) -> float:
    """Radial (line-of-sight) component of `velocity_mps`, from `sin_az` alone.

    See the module docstring: exact under `e2e.ml.scenes.sample_scene`'s fixed radar
    pose (origin, boresight +x, ULA axis +y), not a general-pose reconstruction.
    """
    cos_az = math.sqrt(max(0.0, 1.0 - sin_az ** 2))
    return float(velocity_mps[0]) * cos_az + float(velocity_mps[1]) * sin_az


def _int_hist(values: Sequence[int]) -> Dict[int, int]:
    """Histogram over small non-negative integer counts (targets/frame, clutter/frame, ...)."""
    counter = Counter(int(v) for v in values)
    return {k: counter[k] for k in sorted(counter)}


def _hist(values: Sequence[float], bins: int = 20, value_range=None) -> Dict[str, list]:
    if not values:
        return {"bin_edges": [], "counts": []}
    counts, edges = np.histogram(np.asarray(values, dtype=np.float64), bins=bins, range=value_range)
    return {"bin_edges": [float(e) for e in edges], "counts": [int(c) for c in counts]}


def _stats3(values: Sequence[float]) -> Dict[str, float]:
    arr = np.asarray(values, dtype=np.float64)
    return {
        "mean": float(arr.mean()), "min": float(arr.min()), "max": float(arr.max()),
        "std": float(arr.std()), "n": int(arr.size),
    }


# --------------------------------------------------------------------------------
# Per-frame record extraction (meta-only)
# --------------------------------------------------------------------------------
def _frame_record(meta: Dict[str, Any], grid: Dict[str, float]) -> Dict[str, Any]:
    """One frame's `meta` -> a flat record of everything `_aggregate` needs.

    `grid` is `{"n_range", "n_azimuth", "max_range_m", "range_bin_m", "az_bin"}`.
    """
    targets = meta.get("targets", [])
    extras = meta.get("target_extras", [])
    scene = meta.get("scene", {})

    class_counts: Counter = Counter()
    ranges: List[float] = []
    sin_azs: List[float] = []
    rcs_by_class: Dict[str, List[float]] = {}
    radial_by_class: Dict[str, List[float]] = {}
    cells: List[tuple] = []
    edge_count = 0

    for (r, sin_az, cls), extra in zip(targets, extras):
        class_counts[cls] += 1
        ranges.append(r)
        sin_azs.append(sin_az)
        rcs_by_class.setdefault(cls, []).append(float(extra["rcs_dbsm"]))
        radial_by_class.setdefault(cls, []).append(_radial_velocity(sin_az, extra["velocity_mps"]))

        ci = min(int(r / grid["range_bin_m"]), grid["n_range"] - 1)
        cj = min(int((sin_az + 1.0) / grid["az_bin"]), grid["n_azimuth"] - 1)
        cells.append((ci, cj))
        if ci < 1 or ci >= grid["n_range"] - 1 or cj < 1 or cj >= grid["n_azimuth"] - 1:
            edge_count += 1

    overlap = False
    for i in range(len(cells)):
        for j in range(i + 1, len(cells)):
            if max(abs(cells[i][0] - cells[j][0]), abs(cells[i][1] - cells[j][1])) <= 2:
                overlap = True
                break
        if overlap:
            break

    n_vehicles = scene.get("n_vehicles", 0)
    n_pedestrians = scene.get("n_pedestrians", 0)

    return {
        "n_targets": len(targets),
        "n_vehicles": n_vehicles,
        "n_pedestrians": n_pedestrians,
        "n_clutter": scene.get("n_clutter", 0),
        "class_counts": class_counts,
        "ranges": ranges,
        "sin_azs": sin_azs,
        "rcs_by_class": rcs_by_class,
        "radial_by_class": radial_by_class,
        "edge_count": edge_count,
        "overlap": overlap,
        "placement_attempts": scene.get("placement_attempts"),
        "mismatch": len(targets) != (n_vehicles + n_pedestrians),
    }


# --------------------------------------------------------------------------------
# Aggregation (per-split and overall use the exact same function)
# --------------------------------------------------------------------------------
def _aggregate(records: Sequence[Dict[str, Any]], clamp_cap: float) -> Dict[str, Any]:
    n = len(records)
    if n == 0:
        return {
            "frame_count": 0,
            "targets_per_frame": {"mean": float("nan"), "min": None, "max": None, "hist": {}},
            "class_counts": {}, "vehicle_pedestrian_ratio": float("nan"),
            "clutter_per_frame": {"mean": float("nan"), "min": None, "max": None, "hist": {}},
            "range_hist_m": {"bin_edges": [], "counts": []},
            "sin_az_hist": {"bin_edges": [], "counts": []},
            "rcs_dbsm": {}, "radial_velocity_mps": {},
            "clamp_saturation_rate": float("nan"),
            "footprint_overlap_fraction": float("nan"),
            "edge_target_fraction": float("nan"),
            "placement_attempts": {"mean": float("nan"), "min": None, "max": None},
            "targets_scene_count_mismatches": 0,
            "total_targets": 0,
        }

    targets_per_frame = [r["n_targets"] for r in records]
    clutter_per_frame = [r["n_clutter"] for r in records]
    placement_attempts = [r["placement_attempts"] for r in records if r["placement_attempts"] is not None]
    overlap_frames = sum(1 for r in records if r["overlap"])
    edge_targets = sum(r["edge_count"] for r in records)
    total_targets = sum(targets_per_frame)
    mismatches = sum(1 for r in records if r["mismatch"])

    class_counts: Counter = Counter()
    all_ranges: List[float] = []
    all_sin_az: List[float] = []
    rcs_by_class: Dict[str, List[float]] = {}
    radial_by_class: Dict[str, List[float]] = {}
    for r in records:
        class_counts.update(r["class_counts"])
        all_ranges.extend(r["ranges"])
        all_sin_az.extend(r["sin_azs"])
        for cls, vals in r["rcs_by_class"].items():
            rcs_by_class.setdefault(cls, []).extend(vals)
        for cls, vals in r["radial_by_class"].items():
            radial_by_class.setdefault(cls, []).extend(vals)

    vehicle_n = class_counts.get("vehicle", 0)
    ped_n = class_counts.get("pedestrian", 0)
    if ped_n > 0:
        vehicle_ped_ratio = vehicle_n / ped_n
    elif vehicle_n > 0:
        vehicle_ped_ratio = float("inf")  # degenerate tier (e.g. D0): no pedestrians at all
    else:
        vehicle_ped_ratio = float("nan")

    def _clamp_rate(vals: Sequence[float]) -> float:
        if not vals:
            return float("nan")
        hits = sum(1 for v in vals if abs(abs(v) - clamp_cap) <= CLAMP_TOL * clamp_cap)
        return hits / len(vals)

    all_radial = [v for vals in radial_by_class.values() for v in vals]

    rcs_stats = {cls: _stats3(vals) for cls, vals in rcs_by_class.items()}
    radial_stats = {
        cls: {**_stats3(vals), "mean_abs": float(np.mean(np.abs(vals))), "clamp_rate": _clamp_rate(vals)}
        for cls, vals in radial_by_class.items()
    }

    return {
        "frame_count": n,
        "targets_per_frame": {
            "mean": float(np.mean(targets_per_frame)),
            "min": int(np.min(targets_per_frame)),
            "max": int(np.max(targets_per_frame)),
            "hist": _int_hist(targets_per_frame),
        },
        "class_counts": {"vehicle": vehicle_n, "pedestrian": ped_n},
        "vehicle_pedestrian_ratio": vehicle_ped_ratio,
        "clutter_per_frame": {
            "mean": float(np.mean(clutter_per_frame)),
            "min": int(np.min(clutter_per_frame)),
            "max": int(np.max(clutter_per_frame)),
            "hist": _int_hist(clutter_per_frame),
        },
        "range_hist_m": _hist(all_ranges, bins=20),
        "sin_az_hist": _hist(all_sin_az, bins=20, value_range=(-1.0, 1.0)),
        "rcs_dbsm": rcs_stats,
        "radial_velocity_mps": radial_stats,
        "clamp_saturation_rate": _clamp_rate(all_radial),
        "footprint_overlap_fraction": overlap_frames / n,
        "edge_target_fraction": (edge_targets / total_targets) if total_targets else float("nan"),
        "placement_attempts": {
            "mean": float(np.mean(placement_attempts)) if placement_attempts else float("nan"),
            "min": int(np.min(placement_attempts)) if placement_attempts else None,
            "max": int(np.max(placement_attempts)) if placement_attempts else None,
        },
        "targets_scene_count_mismatches": mismatches,
        "total_targets": total_targets,
    }


# --------------------------------------------------------------------------------
# Flags
# --------------------------------------------------------------------------------
def compute_flags(overall: Dict[str, Any]) -> Dict[str, Any]:
    """Top-of-report flag dict, derived purely from an `_aggregate`-shaped `overall`
    dict -- exposed separately (not inlined in `collect_stats`) so a hand-built
    aggregate (e.g. in a test, or a report re-generated from a saved stats JSON) can
    be checked against the same flag logic without a full manifest/npz pass.
    """
    clamp_rate = overall.get("clamp_saturation_rate", float("nan"))
    overlap_frac = overall.get("footprint_overlap_fraction", float("nan"))
    return {
        "clamp_saturation_rate": clamp_rate,
        "clamp_saturation_flag": bool(clamp_rate > CLAMP_FLAG_THRESHOLD),
        "footprint_overlap_fraction": overlap_frac,
        "footprint_overlap_flag": bool(overlap_frac > OVERLAP_FLAG_THRESHOLD),
        "edge_target_fraction": overall.get("edge_target_fraction", float("nan")),
        "targets_scene_count_mismatches": overall.get("targets_scene_count_mismatches", 0),
    }


# --------------------------------------------------------------------------------
# Optional tensor-level sampling
# --------------------------------------------------------------------------------
def _tensor_sample_stats(manifest_path, split: str, k: int) -> Dict[str, Any]:
    """`k` frames/split (first `k` by filename, deterministic), "rd"-derived input ->
    magnitude dynamic range + measured peak-to-median-floor power ratio (dB).

    See the module docstring for why this is NOT the same quantity as `meta["snr_db"]`.
    """
    from e2e.ml.dataset import RadarFrameDataset

    ds = RadarFrameDataset(manifest_path, split=split, input_format="rd")
    order = sorted(range(len(ds.files)), key=lambda i: ds.files[i])[:k]
    if not order:
        return {"n_sampled": 0}

    dyn_ranges = []
    peak_floor_db = []
    mag_means, mag_mins, mag_maxs = [], [], []
    for idx in order:
        x, _y = ds[idx]
        c = x.shape[0] // 2
        mag = torch.sqrt(x[:c] ** 2 + x[c:] ** 2).detach().cpu().numpy()
        mmin, mmax, mmean = float(mag.min()), float(mag.max()), float(mag.mean())
        mag_mins.append(mmin); mag_maxs.append(mmax); mag_means.append(mmean)
        dyn_ranges.append(20.0 * math.log10(max(mmax, _EPS) / max(mmin, _EPS)))

        power = mag ** 2
        peak_power = float(power.max())
        median_power = float(np.median(power))
        peak_floor_db.append(10.0 * math.log10(max(peak_power, _EPS) / max(median_power, _EPS)))

    return {
        "n_sampled": len(order),
        "input_magnitude": {
            "mean_of_frame_means": float(np.mean(mag_means)),
            "min": float(np.min(mag_mins)),
            "max": float(np.max(mag_maxs)),
        },
        "dynamic_range_db": {
            "mean": float(np.mean(dyn_ranges)), "min": float(np.min(dyn_ranges)), "max": float(np.max(dyn_ranges)),
        },
        "peak_to_median_floor_db": {
            "mean": float(np.mean(peak_floor_db)), "min": float(np.min(peak_floor_db)), "max": float(np.max(peak_floor_db)),
        },
    }


# --------------------------------------------------------------------------------
# Public entry point: collect_stats
# --------------------------------------------------------------------------------
def collect_stats(manifest_path, *, tensor_sample_per_split: Optional[int] = None) -> Dict[str, Any]:
    """Manifest/meta-only statistical pass over `manifest_path`'s corpus.

    Returns a dict with `manifest_path`, `config_name`, `tier`, `n_frames_total`,
    `grid`, `max_velocity_mps`, `clamp_cap_mps`, `splits` (per-split aggregate --
    see `_aggregate`), `overall` (same shape, across all splits), `flags` (see
    `compute_flags`, plus `zero_class_warnings`), and, if `tensor_sample_per_split`
    is given, `tensor_sample` (per-split, see `_tensor_sample_stats`).
    """
    manifest_path = Path(manifest_path)
    with open(manifest_path) as f:
        manifest = json.load(f)

    from e2e.ml.radar_config import RadarConfig

    cfg = RadarConfig.from_dict(manifest["config"])
    clamp_cap = CLAMP_FRAC * cfg.max_velocity_mps

    grid_meta = manifest["grid"]
    n_range = int(grid_meta["n_range"])
    n_azimuth = int(grid_meta["n_azimuth"])
    max_range_m = float(grid_meta.get("max_range_m", cfg.max_range_m))
    grid = {
        "n_range": n_range, "n_azimuth": n_azimuth, "max_range_m": max_range_m,
        "range_bin_m": max_range_m / n_range, "az_bin": 2.0 / n_azimuth,
    }

    dataset_dir = manifest_path.parent
    splits_out: Dict[str, Any] = {}
    all_records: List[Dict[str, Any]] = []
    for split, files in manifest["files"].items():
        records = []
        for fname in files:
            with np.load(dataset_dir / fname) as data:
                meta = json.loads(str(data["meta"].item()))
            records.append(_frame_record(meta, grid))
        splits_out[split] = _aggregate(records, clamp_cap)
        all_records.extend(records)

    overall = _aggregate(all_records, clamp_cap)

    zero_class_warnings: List[str] = []
    for split, s in splits_out.items():
        if s["frame_count"] == 0:
            continue
        for cls in LABEL_CLASSES:
            if s["class_counts"].get(cls, 0) == 0:
                zero_class_warnings.append(f"{split}: 0 {cls} targets")
    if overall["frame_count"] > 0:
        for cls in LABEL_CLASSES:
            if overall["class_counts"].get(cls, 0) == 0:
                zero_class_warnings.append(f"overall: 0 {cls} targets")

    flags = compute_flags(overall)
    flags["zero_class_warnings"] = zero_class_warnings

    stats: Dict[str, Any] = {
        "manifest_path": str(manifest_path),
        "config_name": manifest["config"]["name"],
        "tier": manifest["tier"],
        "n_frames_total": sum(s["frame_count"] for s in splits_out.values()),
        "grid": grid,
        "max_velocity_mps": cfg.max_velocity_mps,
        "clamp_cap_mps": clamp_cap,
        "splits": splits_out,
        "overall": overall,
        "flags": flags,
    }

    if tensor_sample_per_split:
        stats["tensor_sample"] = {
            split: _tensor_sample_stats(manifest_path, split, tensor_sample_per_split)
            for split in manifest["files"]
        }

    return stats


# --------------------------------------------------------------------------------
# compare_tiers: cross-tier table + monotonicity notes
# --------------------------------------------------------------------------------
_MONOTONIC_NON_DECREASING_KEYS = ("targets_per_frame_mean", "clutter_per_frame_mean")


def compare_tiers(stats_list: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    """Cross-tier comparison table (counts/speeds/clamp rates side by side) +
    monotonicity notes, from a list of `collect_stats(...)` return dicts (any order --
    sorted here by `tier` name, e.g. D0 < D1 < D2 < D3).

    `targets/frame` and `clutter/frame` should be non-decreasing D0->D3 (design doc
    section 4): `monotonicity_notes` lists every adjacent-tier pair (in sorted order)
    where that expectation is violated, as human-readable strings (empty list == no
    violations found).
    """
    ordered = sorted(stats_list, key=lambda s: s["tier"])
    rows = []
    for s in ordered:
        overall = s["overall"]
        rows.append({
            "tier": s["tier"],
            "config": s["config_name"],
            "frame_count": overall["frame_count"],
            "targets_per_frame_mean": overall["targets_per_frame"]["mean"],
            "clutter_per_frame_mean": overall["clutter_per_frame"]["mean"],
            "vehicle_pedestrian_ratio": overall["vehicle_pedestrian_ratio"],
            "clamp_saturation_rate": overall["clamp_saturation_rate"],
            "footprint_overlap_fraction": overall["footprint_overlap_fraction"],
        })

    def _violations(key: str) -> List[str]:
        out = []
        for a, b in zip(rows[:-1], rows[1:]):
            va, vb = a[key], b[key]
            if (isinstance(va, float) and math.isnan(va)) or (isinstance(vb, float) and math.isnan(vb)):
                continue
            if vb < va:
                out.append(f"{a['tier']}->{b['tier']}: {key} decreased ({va:.4g} -> {vb:.4g})")
        return out

    monotonicity_notes = {key: _violations(key) for key in _MONOTONIC_NON_DECREASING_KEYS}
    return {"rows": rows, "monotonicity_notes": monotonicity_notes}


# --------------------------------------------------------------------------------
# Markdown rendering
# --------------------------------------------------------------------------------
def _fmt(v, spec: str = "{:.4g}") -> str:
    if v is None:
        return "n/a"
    if isinstance(v, float):
        if math.isnan(v):
            return "n/a"
        if math.isinf(v):
            return "inf" if v > 0 else "-inf"
        return spec.format(v)
    return str(v)


def _table(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> List[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(_fmt(c) if not isinstance(c, str) else c for c in row) + " |")
    return lines


def write_report(stats: Dict[str, Any], out_path) -> Path:
    """Render `collect_stats(...)`'s output as a readable markdown report at `out_path`."""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    overall = stats.get("overall", {})
    flags = stats.get("flags") or compute_flags(overall)
    splits = stats.get("splits", {})
    split_names = list(splits)

    lines: List[str] = []
    lines.append("# Corpus Statistical Validation Report")
    lines.append("")
    lines.append(f"- **Manifest:** `{stats.get('manifest_path', 'n/a')}`")
    lines.append(f"- **Config:** `{stats.get('config_name', 'n/a')}`  **Tier:** `{stats.get('tier', 'n/a')}`")
    lines.append(f"- **Total frames:** {stats.get('n_frames_total', 'n/a')}")
    lines.append(f"- **max_velocity_mps:** {_fmt(stats.get('max_velocity_mps'))}  "
                 f"**clamp cap (0.8x):** {_fmt(stats.get('clamp_cap_mps'))}")
    lines.append("")

    lines.append("## Flags")
    lines.append("")
    clamp_mark = " **[FLAG]**" if flags.get("clamp_saturation_flag") else ""
    overlap_mark = " **[FLAG]**" if flags.get("footprint_overlap_flag") else ""
    lines.append(f"- Clamp saturation rate (overall, threshold {CLAMP_FLAG_THRESHOLD:g}): "
                 f"{_fmt(flags.get('clamp_saturation_rate'))}{clamp_mark}")
    lines.append(f"- Footprint overlap fraction (overall, threshold {OVERLAP_FLAG_THRESHOLD:g}): "
                 f"{_fmt(flags.get('footprint_overlap_fraction'))}{overlap_mark}")
    lines.append(f"- Edge-target fraction (overall): {_fmt(flags.get('edge_target_fraction'))}")
    lines.append(f"- Targets/scene-count mismatches (overall): {_fmt(flags.get('targets_scene_count_mismatches'))}")
    warnings = flags.get("zero_class_warnings") or []
    if warnings:
        lines.append("- Zero-class warnings:")
        for w in warnings:
            lines.append(f"  - {w}")
    else:
        lines.append("- Zero-class warnings: none")
    lines.append("")

    lines.append("## Per-split summary")
    lines.append("")
    rows = []
    for split in split_names + (["overall"] if "overall" in stats else []):
        s = splits.get(split, overall) if split == "overall" else splits[split]
        rows.append([
            split, s["frame_count"], _fmt(s["targets_per_frame"]["mean"]),
            s["targets_per_frame"]["min"], s["targets_per_frame"]["max"],
            s["class_counts"].get("vehicle", 0), s["class_counts"].get("pedestrian", 0),
            _fmt(s["vehicle_pedestrian_ratio"]), _fmt(s["clutter_per_frame"]["mean"]),
            _fmt(s["placement_attempts"]["mean"]),
        ])
    lines += _table(
        ["split", "frames", "targets/frame mean", "min", "max", "vehicle", "pedestrian",
         "veh:ped", "clutter/frame mean", "placement attempts mean"],
        rows,
    )
    lines.append("")

    lines.append("## RCS distribution (dBsm)")
    lines.append("")
    rcs_rows = []
    for split in list(split_names) + ["overall"]:
        s = splits[split] if split in splits else overall
        for cls, st in s.get("rcs_dbsm", {}).items():
            rcs_rows.append([split, cls, _fmt(st["mean"]), _fmt(st["std"]), _fmt(st["min"]), _fmt(st["max"]), st["n"]])
    lines += _table(["split", "class", "mean", "std", "min", "max", "n"], rcs_rows)
    lines.append("")

    lines.append("## Radial velocity / clamp saturation")
    lines.append("")
    lines.append(f"(radial velocity is a LOS-projection approximation; see module docstring. "
                 f"Clamp cap = 0.8 * max_velocity_mps = {_fmt(stats.get('clamp_cap_mps'))} m/s.)")
    lines.append("")
    vel_rows = []
    for split in list(split_names) + ["overall"]:
        s = splits[split] if split in splits else overall
        for cls, st in s.get("radial_velocity_mps", {}).items():
            vel_rows.append([split, cls, _fmt(st["mean_abs"]), _fmt(st["min"]), _fmt(st["max"]), _fmt(st["clamp_rate"]), st["n"]])
    lines += _table(["split", "class", "mean|v_r|", "min", "max", "clamp_rate", "n"], vel_rows)
    lines.append("")

    lines.append("## Footprint overlap / edge fraction")
    lines.append("")
    fo_rows = []
    for split in list(split_names) + ["overall"]:
        s = splits[split] if split in splits else overall
        fo_rows.append([split, _fmt(s["footprint_overlap_fraction"]), _fmt(s["edge_target_fraction"])])
    lines += _table(["split", "overlap_fraction", "edge_target_fraction"], fo_rows)
    lines.append("")

    grid = stats.get("grid", {})
    lines.append("## Range / sin(az) histograms (overall)")
    lines.append("")
    lines.append(f"Grid: n_range={grid.get('n_range')} n_azimuth={grid.get('n_azimuth')} "
                 f"max_range_m={_fmt(grid.get('max_range_m'))} range_bin_m={_fmt(grid.get('range_bin_m'))} "
                 f"az_bin={_fmt(grid.get('az_bin'))}")
    lines.append("")
    r_hist = overall.get("range_hist_m", {})
    if r_hist.get("counts"):
        edges = r_hist["bin_edges"]
        lines += _table(
            ["range bin (m)", "count"],
            [[f"[{edges[i]:.2f}, {edges[i+1]:.2f})", r_hist["counts"][i]] for i in range(len(r_hist["counts"]))],
        )
    az_hist = overall.get("sin_az_hist", {})
    if az_hist.get("counts"):
        edges = az_hist["bin_edges"]
        lines.append("")
        lines += _table(
            ["sin(az) bin", "count"],
            [[f"[{edges[i]:.2f}, {edges[i+1]:.2f})", az_hist["counts"][i]] for i in range(len(az_hist["counts"]))],
        )
    lines.append("")

    tensor_sample = stats.get("tensor_sample")
    if tensor_sample:
        lines.append("## Tensor-level sample (derived RD input; NOT the synthesis snr_db)")
        lines.append("")
        ts_rows = []
        for split, ts in tensor_sample.items():
            if ts.get("n_sampled", 0) == 0:
                ts_rows.append([split, 0, "n/a", "n/a", "n/a"])
                continue
            ts_rows.append([
                split, ts["n_sampled"], _fmt(ts["dynamic_range_db"]["mean"]),
                _fmt(ts["peak_to_median_floor_db"]["mean"]), _fmt(ts["input_magnitude"]["mean_of_frame_means"]),
            ])
        lines += _table(
            ["split", "n_sampled", "dyn_range_db mean", "peak/median floor dB mean", "|input| mean"],
            ts_rows,
        )
        lines.append("")

    out_path.write_text("\n".join(lines) + "\n")
    return out_path


def write_comparison_report(comparison: Dict[str, Any], out_path) -> Path:
    """Render `compare_tiers(...)`'s output as a readable markdown cross-tier report."""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines: List[str] = ["# Cross-Tier Corpus Comparison", ""]
    rows = comparison.get("rows", [])
    table_rows = [
        [r["tier"], r["config"], r["frame_count"], _fmt(r["targets_per_frame_mean"]),
         _fmt(r["clutter_per_frame_mean"]), _fmt(r["vehicle_pedestrian_ratio"]),
         _fmt(r["clamp_saturation_rate"]), _fmt(r["footprint_overlap_fraction"])]
        for r in rows
    ]
    lines += _table(
        ["tier", "config", "frames", "targets/frame", "clutter/frame", "veh:ped",
         "clamp_saturation_rate", "footprint_overlap_fraction"],
        table_rows,
    )
    lines.append("")
    lines.append("## Monotonicity notes (expected non-decreasing D0->D3)")
    lines.append("")
    notes = comparison.get("monotonicity_notes", {})
    any_violation = False
    for key, violations in notes.items():
        if violations:
            any_violation = True
            lines.append(f"- **{key}**:")
            for v in violations:
                lines.append(f"  - {v}")
        else:
            lines.append(f"- {key}: OK (non-decreasing across all tiers)")
    if not any_violation:
        lines.append("")
        lines.append("No monotonicity violations found.")

    out_path.write_text("\n".join(lines) + "\n")
    return out_path


# --------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------
def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m e2e.ml.stats_report",
        description="Statistical-validation reporter for e2e.ml radar dataset corpora.",
    )
    p.add_argument("--manifest", default=None, help="path to a generate_dataset manifest.json")
    p.add_argument("--out", default=None,
                   help="output markdown path (default: <manifest dir>/stats_report.md, or "
                        "./combined_stats_report.md for --compare)")
    p.add_argument("--tensor-sample", type=int, default=None, dest="tensor_sample",
                   help="optional tensor-level sample size per split (see collect_stats)")
    p.add_argument("--compare", nargs="+", default=None, metavar="MANIFEST",
                   help="compare multiple manifests' corpus stats (cross-tier table + "
                        "monotonicity notes); mutually exclusive with running a single report")
    return p


def main(argv: Optional[List[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)

    if args.compare:
        stats_list = [collect_stats(m, tensor_sample_per_split=args.tensor_sample) for m in args.compare]
        comparison = compare_tiers(stats_list)
        out_path = Path(args.out) if args.out else Path("combined_stats_report.md")
        write_comparison_report(comparison, out_path)
        print(f"wrote {out_path}")
        return 0

    if not args.manifest:
        print("either --manifest or --compare is required", file=sys.stderr)
        return 2

    stats = collect_stats(args.manifest, tensor_sample_per_split=args.tensor_sample)
    out_path = Path(args.out) if args.out else Path(args.manifest).parent / "stats_report.md"
    write_report(stats, out_path)
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
